import csv
import os
import glob
import json
from datetime import datetime
import requests
from bs4 import BeautifulSoup

from config import (driver, date, setup_logging)

# Set output_folder to folder created in config.py
output_folder = "output"
shop_name = "elektromarket"

# Define CSV filenames
csv_filename = f"output/{shop_name}_{date}.csv"
log_filename = f"output/log_tech_details_{shop_name}_{date}.log"

# Setup logger:
logger = setup_logging(log_filename)
logger.info("Starting technical details retrieval script.")
logger.info("CSV File: {}", csv_filename)
logger.info("Log File: {}", log_filename)

# Find the latest CSV file generated by the first script
csv_pattern = os.path.join(output_folder, f"{shop_name}_*.csv")
csv_files = glob.glob(csv_pattern)
if not csv_files:
    logger.error("No CSV files found matching the pattern {}", csv_pattern)
    exit(1)

def extract_date(filename):
    """
    Extracts date from the filename assuming the format shop_name_dd-mm-yyyy-hh-mm-ss.csv.
    """
    base = os.path.basename(filename)
    # File name format: {shop_name}_dd-mm-yyyy-hh-mm-ss.csv
    date_str = base.replace(f"{shop_name}_", "").replace(".csv", "")
    try:
        return datetime.strptime(date_str, "%d-%m-%Y-%H-%M-%S")
    except ValueError:
        return None

csv_files_with_date = [(file, extract_date(file)) for file in csv_files if extract_date(file) is not None]
if not csv_files_with_date:
    logger.error("None of the CSV files have a valid date format.")
    exit(1)
csv_files_with_date.sort(key=lambda x: x[1], reverse=True)
latest_csv_file = csv_files_with_date[0][0]
logger.info("Selected CSV file: {}", latest_csv_file)

# Load product links from the CSV file
product_data = []
with open(latest_csv_file, mode="r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        if row.get("product_link"):
            product_data.append({
                "product_link": row["product_link"],
            })
logger.info("Found {} products to process.", len(product_data))

def scrape_tech_details(url):
    """
    This function opens a product page and attempts to retrieve all technical details.

    """
    tech_details = {}
    try:
        requested_page = requests.get(url)
        requested_page.raise_for_status()
        soup = BeautifulSoup(requested_page.text, 'html.parser')


        # Search for an item containing technical data
        product_details_table = soup.find(class_="tab-pane fade active in")
        if not product_details_table:
            logger.warning("No table found for URL: {}", url)
            return tech_details

        #Technical Data Search
        for table_title in product_details_table.find_all("h2"):
            if table_title.text.strip() == "Dane techniczne":
                table = table_title.find_next_sibling("table")
                if table:
                    for detail in table.find_all("tr"):
                        columns = detail.find_all("td")
                        if len(columns) == 2:
                            key = columns[0].get_text(strip=True)
                            value = columns[1].get_text(strip=True)
                            tech_details[key] = value
                        else:
                            logger.warning("Error while reading parameters, incorrect number of columns: {}", url)

    except Exception as e:
        logger.error("Error opening URL {}: {}", url, e)
    return tech_details


# Prepare the output CSV file for technical details in the output folder
tech_csv_filename = os.path.join(output_folder, f"tech_details_{shop_name}_{date}.csv")
output_fieldnames = ["product_link", "tech_details"]

with open(tech_csv_filename, mode="w", newline="", encoding="utf-8") as tech_csvfile:
    writer = csv.DictWriter(tech_csvfile, fieldnames=output_fieldnames)
    writer.writeheader()
    for item in product_data:
        url = item["product_link"]
        logger.info("Processing: {}", url)
        details = scrape_tech_details(url)
        writer.writerow({
            "product_link": url,
            "tech_details": json.dumps(details, ensure_ascii=False)
        })

logger.complete()
logger.info("Technical details retrieval completed. Data saved in file: {}", tech_csv_filename)

